/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProyectoGUI;

/**
 *
 * @author pilco
 */
public class Presentacion extends javax.swing.JPanel {

    /**
     * Creates new form Presentacion
     */
public Presentacion() {
    initComponents();
    String texto = "<span style='font-size:9px;'>"
            + "<span style='color:#007BFF;'>Instrucciones:</span><br>"
            + "Para generar un caracter en el Traductor Brialle-Español, "
            + "dibujar en el cajetín y a continuación clickear "
            + "“Generar carácter”. "
            + "Para facilitar la escritura se encuentran botones que "
            + "generan los caracteres para letras, números, mayúsculas y "
            + "signos de puntuación. <br><br>"
            + "<span style='color:#007BFF;'>Atajos:</span><br>"
            + "<ul style='font-size:9px; margin-left: 20px;'>"
            + "<li>Número (cualquier longitud de cifras) -> Botón \"Números\" + cualquier cantidad de números</li>"
            + "<li>Letras mayúsculas -> Botón \"Mayúsculas\" + cualquier letra</li>"
            + "<li>Letras después de un número -> Botón \"Letra\" + cualquier letra</li>"
            + "<li>Letras mayúsculas después de un número -> Botón \"Letra\" + Botón \"Mayúsculas\" + cualquier letra</li>"
            + "<li>Símbolos -> Botón \"Símbolo\" + símbolo</li>"
            + "</ul>"
            + "<span style='font-size:9px'>(Ver “Diccionario para recordar” para conocer qué caracteres "
            + "están soportados)</span><br>"
            + "<span style='color:#007BFF;'>Atajos de teclado:</span><br>"
            + "<ol style='font-size:9px; margin-left: 20px;'>"
            + "<li>Tecla ESC -> Cerrar el programa</li>"
            + "<li>Tecla I -> Dirigir a la pestaña de Inicio</li>"
            + "<li>Tecla E -> Dirigir a la pestaña de Esp - Bra</li>"
            + "<li>Tecla B -> Dirigir a la pestaña de Bra - Esp</li>"
            + "</ol>"
            + "</span>";

    Descripcion.setText("<html>" + texto + "</html>");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 595));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoGrupo_peque.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        jLabel2.setText("BUG BUSTERS");

        Descripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public String StrToHtml(String texto) {
        return "<html><p>" + texto + "</p></html>";
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
